sudo: required
services:
    - docker

before_install:
    - docker build -t tsaabyy/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true tsaabyy/docker-react-test npm run test

language: generic
